# -*- coding: utf-8 -*-
"""Volume_Trend_2022_2024_ver5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HImWqIvwQ2afwQ9i3YId9b9YzGc-M9hB
"""

# !pip install dask[complete] pandas plotly dash openpyxl

## Streamlit Dashboard:

# Volume & Volume by Transaction by MCC type
# Data table 6- month basis

import streamlit as st
import pandas as pd
import plotly.graph_objs as go

file_path = '22-24 Jan-dec live accts Yearly avg_streamlit.xlsx'

mcc_labels = {
    7230: "Beauty Services", 5812: "Restaurants", 7216: "Dry Cleaning", 5499: "Specialty Foods",
    5999: "Misc. Retail", 7297: "Massage", 5691: "Clothing Stores", 8021: "Dentists", 8099: "Medical Services",
    5621: "Women's Apparel", 5814: "Fast Food", 8299: "Educational Services", 7538: "Auto Repair",
    5921: "Alcohol Stores", 4812: "Telecom Services", 5944: "Jewelry Stores", 5462: "Bakeries",
    5137: "Men’s Clothing", 5310: "Discount Stores", 5631: "Women's Accessories"
}

mcc_options = {"All MCCs": "all"}
mcc_options.update({v: k for k, v in mcc_labels.items()})

## Volume


@st.cache_data
def load_data():
    df = pd.read_excel(file_path, engine='openpyxl')
    return df

df = load_data()

vol_cols = [f'vol {year}{month:02d}' for year in range(2022, 2025) for month in range(1, 13)][:36]
trans_cols = [f'trans {year}{month:02d}' for year in range(2022, 2025) for month in range(1, 13)][:36]

st.title("BCS Account Volume by MCC type")
selected_label = st.selectbox("Choose Business type", list(mcc_options.keys()))
selected_mcc = mcc_options[selected_label]

if selected_mcc == "all":
    df_filtered = df[vol_cols + trans_cols]
    title = "Avg. MCC All"
else:
    df_filtered = df[df["MCC"] == selected_mcc][vol_cols + trans_cols]
    title = f"{selected_label} (MCC {selected_mcc})"

vol_avg = df_filtered[vol_cols].mean()
trans_avg = df_filtered[trans_cols].mean()
month_labels = [col.split()[-1] for col in vol_cols]

data = pd.DataFrame({
    'Month': pd.to_datetime(month_labels, format='%Y%m'),
    'Volume': vol_avg.values,
    'Transaction': trans_avg.values
}).sort_values('Month')

st.subheader("Monthly Volume Line chart")
fig = go.Figure()
fig.add_trace(go.Scatter(x=data['Month'], y=data['Volume'], mode='lines+markers', name='Volume', line=dict(color='green')))
fig.add_trace(go.Scatter(x=data['Month'], y=data['Transaction'], mode='lines+markers', name='Transaction', line=dict(color='blue')))
fig.update_layout(title=title + " - Avg. Monthly Volume", xaxis_title='Month', yaxis_title='Average Value')
st.plotly_chart(fig, use_container_width=True)


## Volume by transaction


fig = go.Figure()
fig.add_trace(go.Scatter(
    x=data['Month'],
    y=data['Transaction'],
    mode='lines+markers',
    name='Volume',
    line=dict(color='blue')
))
fig.update_layout(
    title=title + "Monthly Avg. Volume by Transaction",
    xaxis_title='Month',
    yaxis_title='Average Value',
    height=500
)

st.plotly_chart(fig, use_container_width=True)

st.subheader("Monthly Avg.Volume by Transaction")

## Data table

st.subheader("📋 6 - month basis Volume & Transaction")
data = data.sort_values('Month').reset_index(drop=True)

data['Period'] = (data.index // 6) + 1

grouped = data.groupby('Period').agg({
    'Month': ['min', 'max'],
    'Volume': 'mean',
    'Transaction': 'mean'
}).reset_index()

grouped.columns = ['Period', 'Start', 'End', 'AvgVolume', 'AvgTransaction']
grouped['Month Range'] = grouped['Start'].dt.strftime('%Y-%m') + ' ~ ' + grouped['End'].dt.strftime('%Y-%m')

grouped['AvgVolume'] = grouped['AvgVolume'].apply(lambda x: f"${x:,.0f}")
grouped['AvgTransaction'] = grouped['AvgTransaction'].apply(lambda x: f"{x:,.0f}")

st.table(grouped[['Month Range', 'AvgVolume', 'AvgTransaction']].rename(columns={
    'Month Range': 'Period',
    'AvgVolume': 'Avg. Volume',
    'AvgTransaction': 'Avg. Transaction'
}))

# !pip install streamlit

#import plotly.graph_objs as go

#st.subheader("Monthly Avg.Volume")

#fig = go.Figure()
#fig.add_trace(go.Scatter(
    #x=data['Month'],
    #y=data['Volume'],
    #mode='lines+markers',
    #name='Volume',
    #line=dict(color='black')
#))
#fig.add_trace(go.Scatter(
    #x=data['Month'],
    #y=data['Transaction'],
    #mode='lines+markers',
    #name='Transaction',
    #line=dict(color='blue')
#))
#fig.update_layout(
    #title=title + "Monthly Avg. Volume",
    #xaxis_title='Month',
    #yaxis_title='Average Value',
    #height=500
#)

#st.plotly_chart(fig, use_container_width=True)

#st.subheader("6 - month basis Volume")

#data["Period"] = (data.index // 6) + 1
#summary = data.groupby("Period").agg(
    #Start=("Month", "min"),
    #End=("Month", "max"),
    #AvgVolume=("Volume", "mean")
#).reset_index()

#summary["Period"] = summary["Start"].dt.strftime("%Y-%m") + " ~ " + summary["End"].dt.strftime("%Y-%m")
#summary["AvgVolume"] = summary["AvgVolume"].apply(lambda x: f"{x:,.0f}")

#st.table(summary[["Period", "AvgVolume"]].rename(columns={
    #"Period": "Month Range",
    #"AvgVolume": "Average Volume"
#}))